apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
data:
  config.yaml: |
    istio_namespace: istio-system
    auth:
      strategy: "login"
    server:
      port: 20001
      web_root: /kiali
    external_services:
      tracing:
        url: http://tracing.istio-system.svc.cluster.local/jaeger
      grafana:
        url: http://grafana.istio-system.svc.cluster.local:3000
      prometheus:
        url: http://prometheus:9090
